id: P004619
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG14533
  title: འཇིག་རྟེན་ལ་འཇུག་པའི་བློ་སྦྱོང་།
  author: ''
  volumes:
    ba9c431ed26f469ba217a038ab8476cc:
      image_group_id: I1KG15682
      title: ''
      volume_number: 1
      total_pages: 282
      base_file: v001.txt
